sudo:
  - required

branches:
  only:
  - travis_build

language: python

python: "3.6"

before_install:
  - sudo apt-get install libpnetcdf-dev
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get install mpich
  - sudo apt-get install nco

compiler: g++

install:
  - pip install -r requirements.txt
  - ./patch.py

script:
  - |
    options=$(head inputs/hydro/athinput.straka | grep configure | cut -d' ' -f3-)
    ./configure.py ${options}
  - make
  - ./bin/straka.ex -i ./inputs/hydro/athinput.straka mesh/ix1_bc=outflow
  - ./combine.py -o test
  - ./examples/2d.straka/compare.py straka-test-main.nc examples/2d.straka/straka-default-main.nc
