sudo:
  - required

branches:
  only:
  - travis_build

before_install:
  - sudo apt-get install libpnetcdf-dev
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get install mpich

language:
  - cpp

compiler:
  - g++

script:
  - ./patch.py

  - |
    options=`head inputs/hydro/athinput.straka | grep configure | cut -d' ' -f3-`
    ./configure.py ${options}

  - make
