sudo:
  - required

branches:
  only:
  - travis_build

language: python

python: "3.6"

cache:
  directories:
  - mpich

before_install:
  - sudo apt-get install libpnetcdf-dev
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get install mpich
  - sudo apt-get install nco

compiler: g++

install:
  - pip install -r requirements.txt
  - ./patch.py
  - ln -s /usr/bin/mpicxx ./

script:
  - |
    options=$(head inputs/hydro/athinput.straka | grep configure | cut -d' ' -f3-)
    ./configure.py ${options}
  - make
  - ./bin/straka.ex -i ./inputs/hydro/athinput.straka
  - ./combine.py -o test
  - ./examples/2d.straka/compare.py straka-test-main.nc examples/2d.straka/straka-default-main.nc

  - |
    options=$(head inputs/hydro/athinput.robert | grep configure | cut -d' ' -f3-)
    ./configure.py ${options}
  - make
  - /usr/bin/mpiexec -np 4 ./bin/robert.ex -i ./inputs/hydro/athinput.robert
  - ./combine.py -o test
  - ./examples/2d.robert/compare.py robert-test-main.nc examples/2d.straka/robert-default-main.nc
