sudo:
  - required

branches:
  only:
  - travis_build

before_install:
  - sudo apt-get install libpnetcdf-dev

language:
  - cpp

compiler:
  - g++

script:
  - ./patch.py
  - ./configure.py
  - make
