os: linux

arch: arm64

dist: focal

language: python

python: "3.8"

compiler: g++

branches:
  only:
  - travis_build

before_install:
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get install openmpi-bin
  - sudo apt-get install libpnetcdf-dev
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get install nco

install:
  - pip install -r requirements.txt
  - ./patch.py

script:
  # straka sinking bubble
  - ./configure.py $(head inputs/hydro/athinput.straka | grep configure | cut -d' ' -f3-)
  - make -j2
  - ./bin/straka.ex -i ./inputs/hydro/athinput.straka time/tlim=300
  - ./combine.py -o test
  - ./examples/2d.straka/compare.py straka-test-main.nc examples/2d.straka/straka-default-main.nc

  # robert rising bubble
  - ./configure.py $(head inputs/hydro/athinput.robert | grep configure | cut -d' ' -f3-)
  - make -j2
  - mpiexec -n 2 --oversubscribe ./bin/robert.ex -i ./inputs/hydro/athinput.robert time/tlim=200
  - ./combine.py -o test
  - ./examples/2d.robert/compare.py robert-test-main.nc examples/2d.robert/robert-default-main.nc
