#ifndef LINDAL_SAT_INV_HPP
#define LINDAL_SAT_INV_HPP

/** @file lindal_sat_inv.hpp"
  *
  * This file is automatically generated by make_saturn_lindal92.py
  *
  * @author Cheng Li
  */
namespace Saturn {
  extern int const lindal92_num;
  extern double const lindal92_T[];
  extern double const lindal92_P[];
}

#endif
