/** @file kessler94_impl.hpp
 * @brief Implement Kessler94 Chemistry
 *
 * This file is automatically generated by make_chemistry.py
 *
 * @author Cheng Li
 * @bug No know bugs.
 */

template<typename D1, typename D2>
void Kessler94::AssembleReactionMatrix(Eigen::DenseBase<D1>& rate,
  Eigen::DenseBase<D2>& jac, Real const q[], Real time)
{
  EquationOfState *peos = pmy_block->peos;
  Thermodynamics *pthermo = pmy_block->pthermo;
  Real cvt = GetCvTotal(q);

  int iT = index_[0];
  Real T = q[iT];
  int iqv = index_[1];
  Real qv = q[iqv];
  int iqc = index_[2];
  Real qc = q[iqc];
  int iqp = index_[3];
  Real qp = q[iqp];

  pthermo->SaturationSurplus(dqsat_.data(), q, VariableType::chem);
  Real dq = dqsat_[iqv];
  Real qs = qv - dq;
  Real Rv = pthermo->GetRd()/pthermo->GetMassRatio(iqv);
  Real lf = pthermo->GetLatent(iqc,T) - Rv*T;
  Real dqsdt = qs/T*lf/(Rv*T);

  Real k1 = coeffs_["condensation"];
  Real k2 = coeffs_["autoconversion"];
  Real k3 = coeffs_["accretion"];
  Real k4 = coeffs_["evaporation"];

  // qc -> qp; k2
  rate(iqc) -= k2*qc;
  jac(iqc,iqc) -= k2;
  
  rate(iqp) += k2*qc;
  jac(iqp,iqc) += k2;
  
  // enthalpy change
  rate(iT) += (k2*qc)*(deltaU_[iqc] - deltaU_[iqp]);
  jac(iT,iqc) += (k2)*(deltaU_[iqc] - deltaU_[iqp])/cvt;
  
  // qc + qp -> 2qp; k3
  rate(iqc) -= k3*qc*qp;
  jac(iqc,iqc) -= k3*qp;
  jac(iqc,iqp) -= k3*qc;
  
  rate(iqp) += k3*qc*qp;
  jac(iqp,iqc) += k3*qp;
  jac(iqp,iqp) += k3*qc;
  
  // enthalpy change
  rate(iT) += (k3*qc*qp)*(deltaU_[iqc] - deltaU_[iqp]);
  jac(iT,iqc) += (k3*qp)*(deltaU_[iqc] - deltaU_[iqp])/cvt;
  jac(iT,iqp) += (k3*qc)*(deltaU_[iqc] - deltaU_[iqp])/cvt;
  
  if (qv < qs) {
    // qc -> qv; k1*(qs - qv)
    rate(iqc) -= k1*(qs - qv)*qc;
    jac(iqc,iT) -= k1*qc*dqsdt;
    jac(iqc,iqv) -= -k1*qc;
    jac(iqc,iqc) -= k1*(-qv + qs);
    
    rate(iqv) += k1*(qs - qv)*qc;
    jac(iqv,iT) += k1*qc*dqsdt;
    jac(iqv,iqv) += -k1*qc;
    jac(iqv,iqc) += k1*(-qv + qs);
    
    // enthalpy change
    rate(iT) += (k1*(qs - qv)*qc)*(deltaU_[iqc] - deltaU_[iqv]);
    jac(iT,iT) += (k1*qc*dqsdt)*(deltaU_[iqc] - deltaU_[iqv])/cvt;
    jac(iT,iqv) += (-k1*qc)*(deltaU_[iqc] - deltaU_[iqv])/cvt;
    jac(iT,iqc) += (k1*(-qv + qs))*(deltaU_[iqc] - deltaU_[iqv])/cvt;
    
    // qp -> qv; k4*(qs - qv)
    rate(iqp) -= k4*(qs - qv)*qp;
    jac(iqp,iT) -= k4*qp*dqsdt;
    jac(iqp,iqv) -= -k4*qp;
    jac(iqp,iqp) -= k4*(-qv + qs);
    
    rate(iqv) += k4*(qs - qv)*qp;
    jac(iqv,iT) += k4*qp*dqsdt;
    jac(iqv,iqv) += -k4*qp;
    jac(iqv,iqp) += k4*(-qv + qs);
    
    // enthalpy change
    rate(iT) += (k4*(qs - qv)*qp)*(deltaU_[iqp] - deltaU_[iqv]);
    jac(iT,iT) += (k4*qp*dqsdt)*(deltaU_[iqp] - deltaU_[iqv])/cvt;
    jac(iT,iqv) += (-k4*qp)*(deltaU_[iqp] - deltaU_[iqv])/cvt;
    jac(iT,iqp) += (k4*(-qv + qs))*(deltaU_[iqp] - deltaU_[iqv])/cvt;
  }
  
  if (qv > qs) {
    // qv -> qc; k1*(qv - qs)
    rate(iqv) -= k1*(qv - qs);
    jac(iqv,iT) -= -k1*dqsdt;
    jac(iqv,iqv) -= k1;
    
    rate(iqc) += k1*(qv - qs);
    jac(iqc,iT) += -k1*dqsdt;
    jac(iqc,iqv) += k1;
    
    // enthalpy change
    rate(iT) += (k1*(qv - qs))*(deltaU_[iqv] - deltaU_[iqc]);
    jac(iT,iT) += (-k1*dqsdt)*(deltaU_[iqv] - deltaU_[iqc])/cvt;
    jac(iT,iqv) += (k1)*(deltaU_[iqv] - deltaU_[iqc])/cvt;
  }

}
